Feature/profile page template
w3c/w3c-website-templates-bundle pull request #115
Opened 2023-07-31 10:38 UTC by NicolaSaunders

2023-08-09 13:03 UTC, jean-gui requested changes
I think some cleanup needs to be done: _group.scss seems unused, and the page for group details in the design system seems to duplicate what's in the profile one. I don't know if other files need to be cleaned up as well.

I'm also unsure about the name "profile", its purpose doesn't seem very clear. I don't know what would be better though.

Other than that this looks good to me.

2023-10-03 12:57 UTC, jean-gui commented
> I think some cleanup needs to be done: _group.scss seems unused, and the page for group details in the design system seems to duplicate what's in the profile one. I don't know if other files need to be cleaned up as well.
> 
> I'm also unsure about the name "profile", its purpose doesn't seem very clear. I don't know what would be better though.
> 
> Other than that this looks good to me. Note that I've added a twig template under templates/pages for this.
> 
> Can you rebase the branch?

@NicolaSaunders any news on that?

2023-11-16 11:58 UTC, NicolaSaunders commented
Apologies for the delay on this one @jean-gui but I have hopefully addressed your requested changes and think this is ready for a further review

2023-11-22 10:31 UTC, jean-gui approved these changes

2023-11-22 10:31 UTC, merged