replace editors with WG
w3c/w3c-website-templates-bundle pull request #124
Opened 2023-09-26 12:37 UTC by deniak

Following discussions on https://github.com/w3c/w3c-website/issues/422#issuecomment-1735403777-permalink, that PR replaces the editors list with the group delivering the spec.

Fix https://github.com/w3c/w3c-website/issues/422

2023-09-26 12:49 UTC, vivienlacourba approved these changes
Change looks good. FYI is that something you confirmed with Coralie?

2023-09-26 12:49 UTC, soryny682 commented
![Uploading Screenshot_2023-09-26-16-47-35-22_d67bbc54277d65f0e377b6258dc8a45d.jpg…]()

2023-09-26 12:49 UTC, soryny682 commented
So good

2023-09-26 13:39 UTC, deniak commented
@koalie, That PR updates the [/TR](https://www.w3.org/TR/) to replace the list of editors with the WG delivering the spec.
I'm attaching a screenshot of the change. Does it look to you?

<img width="639" alt="Screenshot 2023-09-26 at 17 34 19" src="https://github.com/w3c/w3c-website-templates-bundle/assets/1696128/5e7e6f97-9261-49cf-bb75-bc42a59f837f">

2023-09-27 07:32 UTC, koalie commented
> On 26 Sep 2023, at 15:39 , Denis Ah-Kang ***@***.***> wrote:
> 
> 
> @koalie, That PR updates the /TR to replace the list of editors with the WG delivering the spec.
> I'm attaching a screenshot of the change. Does it look to you?

Yes!

Coralie

> 
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.
> 

--
Coralie Mercier  -  Head of W3C Marketing & Communications 
***@***.*** - https://www.w3.org/People/Coralie/

2023-09-27 09:17 UTC, vivienlacourba requested changes

2023-09-27 10:43 UTC, deniak commented on templates/components/listings/publications/tr_card.html.twig
> +    {% if spec.deliverers|filter(d => d.group.shortname not in ['unknownwg', 'hypertextcgmember'] and d.group.groupType != 'coord')|length > 0 %}
@vivienlacourba you are right. I updated the deliverer for these specs and removed the exception.

2023-09-27 13:17 UTC, merged