if the group is closed, add the closing date
w3c/w3c-website-templates-bundle pull request #137
Opened 2024-06-19 13:17 UTC by deniak

2024-06-20 16:25 UTC, vivienlacourba approved these changes

2024-06-20 16:25 UTC, vivienlacourba commented on templates/components/listings/groups/entry.html.twig
> +            {% if group.closed %}<p><em>Group closed on {{ w3c_date_format(group.closedDate)|raw }}</em></p>{% endif %}
It seems important to indicate that the group is closed, so I woudl suggest putting this before the group's description.

```suggestion
            {% if group.closed %}<p><em>Group closed on {{ w3c_date_format(group.closedDate)|raw }}</em></p>{% endif 
            {{ group.description|purify }}
%}
```

2024-06-21 09:29 UTC, jean-gui requested changes
There is a bug here, the {%endif %} is not closed in the right place.

2024-06-21 10:00 UTC, deniak commented
> There is a bug here, the {%endif %} is not closed in the right place.

Thanks @jean-gui, it's fixed now.

2024-06-21 10:27 UTC, jean-gui approved these changes

2024-06-24 04:29 UTC, merged